//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBazzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart
    {
        public int Id { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
